version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - CASTEP
  - Entos
  - Intception
  - Isambard
  - ONETEP
  - ORCID
  - Qcore
ignoreWords: []
import: []
language: en-GB
